[config]

[templates.rofi_colors]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/Themes/Colorschemes/rofi.rasi'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'
