#!/usr/bin/env bash

# Define the options with Nerd Font icons
programs='󰀻  Programs'
files='󱔘  Files'
power_menu='  Power'
setup='  Setup'
utilities='󰧸  Utilities'
keybindings='󰌌  Keybindings'
documentation='󰈙  Documentation'

# Combine options with newline characters
options="$programs\n$files\n$power_menu\n$setup\n$utilities\n$keybindings\n$documentation"

# Pass options to rofi
choice=$(echo -e "$options" | rofi -dmenu -i -p "Go...")
[ $? = 0 ] || exit

# Handle choices based on variables
case "$choice" in
	"$programs")
        	rofi -show drun
        ;;
	"$files")
        	alacritty -e yazi
        ;;
    	"$power_menu")
        	$HOME/.config/rofi/scripts/powermenu
        ;;
    	"$setup")
        	$HOME/.config/rofi/scripts/setup
        ;;   
    	"$utilities")
        	$HOME/.config/rofi/scripts/utils
        ;;   
    	"$calculator")
    		rofi -show calc -modi calc -no-show-match -no-sort
    	;;
	"$clipboard")
		cliphist list | rofi -dmenu | cliphist decode | wl-copy
   	;;
    	"$keybindings")
        ;;
    	"$documentation")
        ;;
    *)
        exit 0
        ;;
esac
