#!/usr/bin/env bash

capture='  Capture'
calculator='󰪚  Calculator'
clipboard='🗎  Clipboard'
activity="  Activity"

options="$capture\n$calculator\n$clipboard\n$activity"

chosen=$(echo -e "$options" | rofi -dmenu -i -p "Select Action:")

case "$chosen" in
	"$capture")
        	$HOME/.config/rofi/scripts/capture
        ;;
    	"$calculator")
    		rofi -show calc -modi calc -no-show-match -no-sort
    	;;
	"$clipboard")
		cliphist list | rofi -dmenu | cliphist decode | wl-copy
   	;;
	"$activity")
		alacritty -e btop 
	;;
	*)
        exit 0
        ;;
esac

